## Numpy - 3
### Agenda 
    1. Sorting
    2. Multiplication
    3. Vectorization
    4. Broadcasting

In [3]:
import numpy as np

## 1. Sorting a Numpy Array


### Sorting a 1D array
#### sort() function


In [4]:
arr = np.array([10,15,2,4,20,13,12,1,5,19])
#sort() function
print(np.sort(arr))

[ 1  2  4  5 10 12 13 15 19 20]


np.sort() does not have a way to sort in descending order
so in order to do descending order sort we do: ascending order sort + reverse the array

In [5]:
print(np.sort(arr)[::-1])

[20 19 15 13 12 10  5  4  2  1]


Another method we can use is by using a negative sign in front of the array to convert the array elements to a negative int before sorting and then remove the negative sign after sorting.

In [6]:
print(arr)
print(np.sort(arr))
print(np.sort(-(arr)))
print(-(np.sort(-(arr))))

[10 15  2  4 20 13 12  1  5 19]
[ 1  2  4  5 10 12 13 15 19 20]
[-20 -19 -15 -13 -12 -10  -5  -4  -2  -1]
[20 19 15 13 12 10  5  4  2  1]


### Sorting a 2D array

In [7]:
#2D array

lst_2d = [
    [5, -7, 46],
    [19, 88, 81],
    [-10, -50, 0],
    [1, 2, 3]
]

arr_2d = np.array(lst_2d)

print(arr_2d)

[[  5  -7  46]
 [ 19  88  81]
 [-10 -50   0]
 [  1   2   3]]


Trying np.sort() in a 2D array sorts it row wise.

In [8]:
print(np.sort(arr_2d))

[[ -7   5  46]
 [ 19  81  88]
 [-50 -10   0]
 [  1   2   3]]


Rows are also called as axis = 1, so we can explicitly give that as a param to the np.sort() and it will sort row wise.

In [9]:
np.sort(arr_2d, axis = 1)

array([[ -7,   5,  46],
       [ 19,  81,  88],
       [-50, -10,   0],
       [  1,   2,   3]])

Colums are also known as axis = 0, To sort an np array columnwise we can explicitly set the axis = 0.

In [10]:
np.sort(arr_2d, axis = 0)

array([[-10, -50,   0],
       [  1,  -7,   3],
       [  5,   2,  46],
       [ 19,  88,  81]])

If we set the axis = None, The sort function will flatten the array and then sort it.

In [11]:
np.sort(arr_2d, axis = None)

array([-50, -10,  -7,   0,   1,   2,   3,   5,  19,  46,  81,  88])

Function argsort() -> It is used to sort the indexes

In [12]:
marks = np.array([67,33,60,55,100,90,78])

names = np.array(['A','B','C','D','E','F','G'])

print(np.sort(marks)) ## Returns the original indices of the elements in sorted order

print(np.argsort(marks))

sorted_index_order = np.argsort(marks) ##List of indices

[ 33  55  60  67  78  90 100]
[1 3 2 0 6 5 4]


In [14]:
print(names[sorted_index_order]) ## This statement will return the list of names of students in ascending order of marks

['B' 'D' 'C' 'A' 'G' 'F' 'E']


To Find out the indices of the maximum and minimum element in an array we use argmax() and argmin() functions

In [20]:
print(np.argmax(marks)) ##Index of the highest marks
print(names[np.argmax(marks)]) ##Name of the person with the highest marks
print(marks[np.argmax(marks)]) ##Marks of the person with the highest marks

4
E
100


In [21]:
print(np.argmin(marks)) ##Index of the lowest marks
print(names[np.argmin(marks)]) ##Name of the person with the lowest marks
print(marks[np.argmin(marks)]) ##Marks of the person with the lowest marks

1
B
33


## 2. Multiplication

### Multiplication of two vectors

In [22]:
a = np.array([5,7,10])
b = np.array([10,100,1000])

print(a * b)


[   50   700 10000]


### Multiplication of scaler with vector

In [23]:
print(a * 5)

[25 35 50]


In [24]:
[5] == 5 ## [5] is a list and 5 is an int both are different objects and not the same

False

In [25]:
np.shape([5])

(1,)

In [26]:
np.shape(5)

()

### Multiplication of two vectors with different lengths

In [28]:
vect_1 = np.array([5, 10])
vect_2 = np.array([2, 4, 8, 16])

print(vect_1 * vect_2)

ValueError: operands could not be broadcast together with shapes (2,) (4,) 

### Elementwise Multiplication of Matrices

In [29]:
m1 = np.array(
    [[1, 2],
    [3, 4]])


m2 = np.array(
    [[10, 1],
    [5, 55]])

print(m1)
print()
print(m2)
print()
print(m1 * m2)

[[1 2]
 [3 4]]

[[10  1]
 [ 5 55]]

[[ 10   2]
 [ 15 220]]


### Dot product

We can use dot() method or @ operator to get the dot product of two vectors.

In [32]:
v1 = np.array([5, 5, 5])
v2 = np.array([2, 3, 5])

print(np.dot(v1, v2)) ##using the dot() function
print(v1@v2) ##using @ operator

50
50


Dot product of 2D matrices or Matrix multiplication



In [33]:
print(m1 @ m2)

[[ 20 111]
 [ 50 223]]


In [34]:
m3 = np.array([
    [1, 3, 5],
    [4, 7, 9]
])

m4 = np.array([
    [11, 12, 10],
    [9, 12, 6]
])

print(m3 @ m4)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)