## Numpy - 3
### Agenda 
    1. Sorting
    2. Multiplication
    3. Vectorization
    4. Broadcasting

In [3]:
import numpy as np

## Sorting a Numpy Array

### Sorting a 1D array
#### sort() function


In [4]:
arr = np.array([10,15,2,4,20,13,12,1,5,19])
#sort() function
print(np.sort(arr))

[ 1  2  4  5 10 12 13 15 19 20]


np.sort() does not have a way to sort in descending order
so in order to do descending order sort we do: ascending order sort + reverse the array

In [5]:
print(np.sort(arr)[::-1])

[20 19 15 13 12 10  5  4  2  1]


Another method we can use is by using a negative sign in front of the array to convert the array elements to a negative int before sorting and then remove the negative sign after sorting.

In [6]:
print(arr)
print(np.sort(arr))
print(np.sort(-(arr)))
print(-(np.sort(-(arr))))

[10 15  2  4 20 13 12  1  5 19]
[ 1  2  4  5 10 12 13 15 19 20]
[-20 -19 -15 -13 -12 -10  -5  -4  -2  -1]
[20 19 15 13 12 10  5  4  2  1]


### Sorting a 2D array

In [7]:
#2D array

lst_2d = [
    [5, -7, 46],
    [19, 88, 81],
    [-10, -50, 0],
    [1, 2, 3]
]

arr_2d = np.array(lst_2d)

print(arr_2d)

[[  5  -7  46]
 [ 19  88  81]
 [-10 -50   0]
 [  1   2   3]]


Trying np.sort() in a 2D array sorts it row wise.

In [8]:
print(np.sort(arr_2d))

[[ -7   5  46]
 [ 19  81  88]
 [-50 -10   0]
 [  1   2   3]]


Rows are also called as axis = 1, so we can explicitly give that as a param to the np.sort() and it will sort row wise.

In [9]:
np.sort(arr_2d, axis = 1)

array([[ -7,   5,  46],
       [ 19,  81,  88],
       [-50, -10,   0],
       [  1,   2,   3]])

Colums are also known as axis = 0, To sort an np array columnwise we can explicitly set the axis = 0.

In [10]:
np.sort(arr_2d, axis = 0)

array([[-10, -50,   0],
       [  1,  -7,   3],
       [  5,   2,  46],
       [ 19,  88,  81]])

If we set the axis = None, The sort function will flatten the array and then sort it.

In [11]:
np.sort(arr_2d, axis = None)

array([-50, -10,  -7,   0,   1,   2,   3,   5,  19,  46,  81,  88])

Function argsort() -> It is used to sort the indexes

In [12]:
marks = np.array([67,33,60,55,100,90,78])

names = np.array(['A','B','C','D','E','F','G'])

print(np.sort(marks)) ## Returns the original indices of the elements in sorted order

print(np.argsort(marks))

sorted_index_order = np.argsort(marks) ##List of indices

[ 33  55  60  67  78  90 100]
[1 3 2 0 6 5 4]


In [14]:
print(names[sorted_index_order]) ## This statement will return the list of names of students in ascending order of marks

['B' 'D' 'C' 'A' 'G' 'F' 'E']
